// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1TUBWm0o76CUVD5czgWf2Sl0VtmlQHM',
    appId: '1:46519691395:web:760e800a6d8d2dd1f713b6',
    messagingSenderId: '46519691395',
    projectId: 'carepaws-fc283',
    authDomain: 'carepaws-fc283.firebaseapp.com',
    storageBucket: 'carepaws-fc283.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRNvGjMcEnemIsaXOwxUB58urefOpz99Y',
    appId: '1:46519691395:android:ad85607248113470f713b6',
    messagingSenderId: '46519691395',
    projectId: 'carepaws-fc283',
    storageBucket: 'carepaws-fc283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3o4ivRZ6ZqiX1rOEnfAnFxrJmO3UT5XM',
    appId: '1:46519691395:ios:7530e26d337de4fbf713b6',
    messagingSenderId: '46519691395',
    projectId: 'carepaws-fc283',
    storageBucket: 'carepaws-fc283.firebasestorage.app',
    iosBundleId: 'com.example.carepaws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3o4ivRZ6ZqiX1rOEnfAnFxrJmO3UT5XM',
    appId: '1:46519691395:ios:7530e26d337de4fbf713b6',
    messagingSenderId: '46519691395',
    projectId: 'carepaws-fc283',
    storageBucket: 'carepaws-fc283.firebasestorage.app',
    iosBundleId: 'com.example.carepaws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP1TUBWm0o76CUVD5czgWf2Sl0VtmlQHM',
    appId: '1:46519691395:web:9766a97497e1b019f713b6',
    messagingSenderId: '46519691395',
    projectId: 'carepaws-fc283',
    authDomain: 'carepaws-fc283.firebaseapp.com',
    storageBucket: 'carepaws-fc283.firebasestorage.app',
  );
}
